[project]
name = "darpy-sdk-snippets"
version = "0.1.0"
description = "Darbot Python SDK Example Snippets"
requires-python = ">=3.10"
dependencies = [
    "darpy-sdk",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["servers", "clients"]

[project.scripts]
darpy-sdk-server = "servers:run_server"
darpy-sdk-client = "clients.stdio_client:main"
darpy-sdk-completion-client = "clients.completion_client:main"
darpy-sdk-direct-execution-server = "servers.direct_execution:main"
darpy-sdk-display-utilities-client = "clients.display_utilities:main"
darpy-sdk-oauth-client = "clients.oauth_client:run"
darpy-sdk-identity-assertion-client = "clients.identity_assertion_client:run"
darpy-sdk-elicitation-client = "clients.url_elicitation_client:run"
